Polymorphism
Folkskrik/CodeLex pull request #11
Opened 2023-03-13 00:03 UTC by Folkskrik

Darīts

2023-03-15 20:14 UTC, ausmoons requested changes

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/AdApp/Advert.cs
> +        public  virtual double Cost()
te ir double, bet pēc tam konvertē uz int. Kāpēc?

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/AdApp/NewspaperAd.cs
> +            return (int)fee;
Kāpēc tev tagad visur atsevišķi vajag int? Uzreiz nevarēji likt int vai atstāt double?

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/AdApp/Poster.cs
> +        private double width;
_width

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/DragRace/Mazda3.cs
> +    private int currentSpeed = 0;
_currentSpeed . Pārskati visur namingu

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/DragRace/Mazda3.cs
> +    public void StartEngine()
Starp metodēm tukša rinda

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/DragRace/Lexus.cs
> +    public void StartEngine()
Tev StartEngine kkur tiek izsaukts?

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Firm/Commission.cs
> +        private double v;
v?

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Firm/Commission.cs
> +        private double v;
Nosaukumiem ir jābūt saprotamiem

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Hierarchy/Employee.cs
> +        private string jobTitle;
Salabo visur private

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/MakeSounds/Parrot.cs
> +            this.sound = sound;
Bez this, kad salabosi nosaukumu

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Persons/Cat.cs
> +using System.Collections.Generic;
Tev visi uzingi tiek lietoti?

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/Persons/Felime.cs
> +using System.Collections.Generic;
Izņem liekos usingus

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/Program.cs
> +                    input = Console.ReadLine();
Te noteikti jādomā par mazāķu metožu izdalīšanu

2023-03-15 20:14 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +            return new Money();
Kāpēc atgriez tukšu Money?

2023-03-16 19:53 UTC, Folkskrik commented on csharp-basics/exercises/Polymorphism/DragRace/Lexus.cs
> +    public void StartEngine()
Jā Program.cs

2023-03-16 19:54 UTC, Folkskrik commented on csharp-basics/exercises/Polymorphism/DragRace/Lexus.cs
> +    public void StartEngine()
Tulīt pielikšu lai ir

2023-03-16 23:01 UTC, Folkskrik commented on csharp-basics/exercises/Polymorphism/VendingMachine/VendingMachine.cs
> +            return new Money();
Ja ievietotā monēta ir derīga, metode pievieno tās vērtību mainīgajam _amount, un tad atgriež jaunu Money objektu. Ja ievietotā monēta nav derīga, metode vienkārši atgriež to pašu Money objektu.

2023-03-16 23:02 UTC, Folkskrik commented on csharp-basics/exercises/Polymorphism/VendingMachine/Program.cs
> +                    input = Console.ReadLine();
Kādā ziņā? mazāk metodes vajag?

2023-03-19 15:06 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/VendingMachine/Program.cs
> +                    input = Console.ReadLine();
Vairāk metodes ar mazāku koda rindu skaitu katrā

2023-03-22 15:53 UTC, EdgarsSalmins approved these changes
saies.. nav perfekti bet būs ok.. :)

2023-03-22 16:03 UTC, merged